version: '2'
services:
  rabbit-1-server:
    image: ttsubo/rabbitmq:juno
    command: /bin/sh -c "/usr/local/bin/start-rabbitmq.sh"
    container_name: rabbit-1-server
    hostname: rabbit-1-server
    environment:
      - ERLANG_COOKIE=abcdefg
    ports:
      - 15672:15672
#    volumes:
#    - ./log/rabbit-1-server:/var/log/rabbitmq
    privileged: true

  rabbit-2-server:
    image: ttsubo/rabbitmq:juno
    command: /bin/sh -c "sleep 5; /usr/local/bin/start-rabbitmq.sh"
    container_name: rabbit-2-server
    hostname: rabbit-2-server
    depends_on:
    - rabbit-1-server
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit-1-server
    ports:
      - 15673:15672
#    volumes:
#    - ./log/rabbit-2-2server:/var/log/rabbitmq
    privileged: true

  rabbit-3-server:
    image: ttsubo/rabbitmq:juno
    command: /bin/sh -c "sleep 10; /usr/local/bin/start-rabbitmq.sh"
    container_name: rabbit-3-server
    hostname: rabbit-3-server
    depends_on:
    - rabbit-1-server
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit-1-server
    ports:
      - 15674:15672
#    volumes:
#    - ./log/rabbit-3-server:/var/log/rabbitmq
    privileged: true

  heat-1-engine:
    image: ttsubo/ubuntu:juno
    command: /bin/sh -c "sleep 20; python heat-engine.py --config-file conf/heat.conf > /log/heat-1-engine.log 2>& 1"
    volumes:
    - ./log:/log
    container_name: heat-1-engine
    hostname: heat-1-engine
    privileged: true

  heat-2-engine:
    image: ttsubo/ubuntu:juno
    command: /bin/sh -c "sleep 25; python heat-engine.py --config-file conf/heat.conf > /log/heat-2-engine.log 2>& 1"
    volumes:
    - ./log:/log
    container_name: heat-2-engine
    hostname: heat-2-engine
    privileged: true

  heat-3-engine:
    image: ttsubo/ubuntu:juno
    command: /bin/sh -c "sleep 30; python heat-engine.py --config-file conf/heat.conf > /log/heat-3-engine.log 2>& 1"
    volumes:
    - ./log:/log
    container_name: heat-3-engine
    hostname: heat-3-engine
    privileged: true

  heat-1-api:
    image: ttsubo/ubuntu:juno
    command: /bin/sh -c "sleep 60; python heat-api.py --config-file conf/heat.conf > /log/heat-1-api.log 2>& 1"
    volumes:
    - ./log:/log
    container_name: heat-1-api
    hostname: heat-1-api
    privileged: true

